### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by kingson999** [r1me/TTesseractOCR4#10]
when build unit FormTesseractOCRImage;
show below error:

![image](https://user-images.githubusercontent.com/26153215/47130418-2b838100-d2cc-11e8-92ba-008283f6154c.png)

**Comment by r1me** [comment]
The only tested and supported Delphi version is the latest one (10.2.3) for VCL.
You can try to declare `PUTF8Char` as `PAnsiChar` as it does for Lazarus:
```
{$IFDEF FPC}
type
  PUTF8Char = PAnsiChar;
{$ENDIF}
```
But I can't guarantee any success.
