### ISSUE TITLE
Cant execute .SynchronizeBegin when calling .SetImage using Pointer to Buffer

### ISSUE THREAD

**Issue by tedsmith** [r1me/TTesseractOCR4#16]
Hi

I'm not sure if this will be seen or not but I'm hoping it might. 

I am trying to utilise the library (which looks amazing by all accounts and thank you for making it) and I can see how it works well via the Freepascal\Lazarus example and the use of .SetImage for a traditional file. 

However, I am trying to use .SetImage in the third form, that being via use of a Pointer to a buffer. 

```
function SetImage(const ABuffer: Pointer; AImageWidth, AImageHeight: Integer;
      ABytesPerPixel: Integer; ABytesPerLine: Integer): Boolean; overload;

```
As far I can tell, the buffer contains valid data from a picture file and the function returns success.  I have passed the various properties like BytesPerLine etc to the function. So all good there. 

So the next step is .RecognizeAsText. This calls .RecognizeInternal and this is where my problem hits. It gets to line 460 which calls : 

`TThread.Synchronize(nil, {$IFDEF FPC}@{$ENDIF}Tesseract.SynchronizeBegin);`

So it then jumps to .SynchronizeBegin which is : 

```
procedure TTesseractOCR4.SynchronizeBegin;
begin
  if Assigned(FOnRecognizeBegin) then
    OnRecognizeBegin(Self);
end; 

```
  

Sadly, it is here where I get the following exception issue : 
![Untitled](https://user-images.githubusercontent.com/1560598/111660506-0d583d00-8806-11eb-958a-d5affac1b7a2.png)

And this is the code that leads up to it, from my own code base: 
![Untitled](https://user-images.githubusercontent.com/1560598/111710130-f256ee80-8840-11eb-96e6-78f5925751e3.png)

I have spent more time than I care to acknowledge trying to work out why this is and I cannot see the problem. And sadly there seems to be few (perhaps no) examples of others using the library with memory buffers. They all seem to use the standard default file based option. 

So I am trying to determine if there is a problem\bug with the library in this regard or whether it is indeed just an error with my code which is highly likely, but having spent so long looking at it I thought I'd raise the possibility that perhaps the library needs a tweak? 

I am using Lazarus 2.0.10 and FPC 3.2.0. 

Many thanks

**Comment by r1me** [comment]
`TessBaseAPISetImage` requires decoded, raw image data, not a Windows bitmap or similar stream made out of a common image format. Encoded image can be loaded to a buffer with leptonica as shown in this [pull request](https://github.com/r1me/TTesseractOCR4/pull/15/commits/8ac24dbb4093eb2adee41123b8622b6609b899c5), with a method called `pixReadMem`

**Comment by tedsmith** [comment]
Many thanks for the direction. 

In this case, I am "getting" a picture file for TesseractOCR4 as a pointer to a buffer that holds a Raster Image of supported pictures files, e.g. JPEG, PNG etc. I have options as to whether the picture is provided as a raw Raster Image (using flags 0x00), or I can use different flags to get different types, as follows : 

0x01: get a memory buffer that starts with an appropriate Windows Bitmap header
0x02: align line offsets at 4-byte boundaries
0x04: vertically flip image, physically (reverse the order of pixel lines in the memory buffer)
0x07: create a standard Windows BMP image (suitable combination of flags 0x01, 0x02, and 0x04)

So, in the example I posted, I was trying it with flag 0x07 which didn't work as per my note. But I have since tried it as 0x00 as well, and still I get the same issue. 

Since my initial post, I have "advanced" to the following, but the same error remains despite correcting some of the earlier problems. I am still totally unclear where the problem lay. 

```
OCRInstance := TTesseractOCR4.Create;
      if OCRInstance.Initialize('tessdata' + PathDelim, 'eng') then
        begin
          //intPixelDimensions := XWF_GetItemInformation(nItemID, XWF_ITEM_INFO_PIXELINDEX, nil);
          hOpenResult := XWF_OpenItem(CurrentVolume, nItemID, $01);
          if hOpenResult > 0 then
            begin
              New(ForOCR_RII);    // Allocate type PRasterImageInfo
              ForOCR_RII.nSize    := BitSizeOf(ForOCR_RII);  // Expect 32 bytes on x86. 36 on x64 because LONG (for nItemID) can be 8 bytes on 64-bit instead of 4.
              ForOCR_RII.nItemID  := nItemID;                // Item ID of picture file
              ForOCR_RII.hItem    := hOpenResult;            // Handle to Item ID
              ForOCR_RII.nFlags   := $00; // Get a Windows Bitmap of the picture file from X-Ways
              ForOCR_RII.nWidth   := 0;   // Will be set by the return value from XWF
              ForOCR_RII.nHeight  := 0;   // Will be set by the return value from XWF
              ForOCR_RII.nResSize := 0;   // Will be set by the return value from XWF

              // Get a pointer to a buffer holding a valid raster BMP image of the picture file
              // and populate values nWidth, nHeight and nResSize
              pPicBuff := XWF_GetRasterImage(ForOCR_RII);

              // If XWF_GetRasterImage worked, buffer will not be null.
              if pPicBuff <> nil then
                begin
                  numBytesPerLine:=  ForOCR_RII.nWidth * 3;
                    if (numBytesPerLine mod 4 <>0) then                // calculate if division by 4 delivers remainder of 0
                      inc(numBytesPerLine, 4-(numBytesPerLine mod 4)); // if no, increase by the number of bytes required to make up the difference

                  // Now pass the BMP buffered image to the OCR engine with the parameters
                  // Will return true if that step succeeded
                  PicReadyForOCR := OCRInstance.SetImage(pPicBuff,
                                                         ForOCR_RII.nWidth,
                                                         ForOCR_RII.nHeight,
                                                         ForOCR_RII.nResSize,
                                                         numBytesPerLine);

                  // And now run the OCR'ing over the image. The text is returned on success                
                  strOCRResult :=  OCRInstance.RecognizeAsText;   // THIS LINE IS THE START OF THE PROBLEMS
                end;
              Dispose(ForOCR_RII);
              Windows.VirtualFree(pPicBuff, 0, MEM_RELEASE);
            end;
        end;                                                              
```

**Comment by tedsmith** [comment]
This is driving me to madness. I just can't see where I am going wrong here. 

Over the weekend I switched the mechanics from using a pointer to a buffer to instead writing the buffer content to a filestream and then using SetImage using the filename mechanism. And I still get exactly the same problem no matter what kind of file I use. PNG, JPEG, etc. All the same error. What I don't understand is that the example project just as a standard PNG file as well, and that doesn't appear to go through any decoding steps or whatever. 

```
// Read the native file item to buffer
                  intBytesRead := XWF_Read(hOpenResult, 0, @InputBytesBuffer[0], ItemSize);
                  // Write the native file out to disk using the above declared stream
                  OutputStreamNative := TFileStream.Create('tempfile.png', fmCreate);
                  WriteSuccess := -1;
                  WriteSuccess := OutputStreamNative.Write(InputBytesBuffer[0], ItemSize);
                  if WriteSuccess > 0 then
                    begin
                      OutputStreamNative.Free;
                      PicReadyForOCR := OCRInstance.SetImage('tempfile.png');
                      if PicReadyForOCR then
                        begin
                          strOCRResult :=  OCRInstance.RecognizeAsText;   // EXCEPTION ARISES HERE AGAIN, STILL
                        end;
                    end;       
```

**Comment by tedsmith** [comment]
I guess it may be easier if I could understand what triggers FOnRecognizeBegin to become assigned, because all I can see the line 

if Assigned(FOnRecognizeBegin) then
    OnRecognizeBegin(Self);     

It seems to be the case that FOnRecognizeBegin is not assigned, in my case. So do we know when or how it becomes assigned? Then I may be able to work out why this constant SIGSEGV keeps arising.

**Comment by tedsmith** [comment]
Someone pointed out that despite creating a Ttesseractocr4 instance using .create, it was also necessary to assign that instance to global bar Tesseract. I had assumed using .create was sufficient but not so. Once I did 

Tesseract := OcrInstance;

Everything worked. 

Thanks again
