### ISSUE TITLE
 Tesseract.SetVariable('tessedit_char_whitelist','0123456789') is not available?

### ISSUE THREAD

**Issue by LaiXiaoYu** [r1me/TTesseractOCR4#20]
delphi xe7
Tesseract.SetVariable('tessedit_char_whitelist','0123456789')
but Tesseract.RecognizeAsText maybe english charactor
so the whitelist is not available?
![1 OCR_S](https://github.com/r1me/TTesseractOCR4/assets/26377175/21e17203-0600-468f-bf26-f9d20b31b289)
![2 OCR_Gray threshold=145 invertcolor](https://github.com/r1me/TTesseractOCR4/assets/26377175/0af369e3-2a45-4f61-ae27-7aec64769b3b)

**Comment by r1me** [comment]
It's a bug in Tesseract 4.0. I recommend switching to latest pre 5 version like 4.1.1
A workaround for this in 4.0 is to initialize Tesseract with "original Tesseract only" engine mode:
`Tesseract.Initialize('tessdata' + PathDelim, 'eng', oemTesseractOnly);`
