### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by mhoude1966** [r1me/TTesseractOCR4#6]
Does it works with Lazarus on Linux ?

Thanks

**Comment by r1me** [comment]
Thank you for reminding me to update the project ;-) Lately, one function in Tesseract's C API was removed, and it was causing failure in loading library. I updated the code and tested all examples in Windows and Linux (Lubuntu 18.04).

![tesseract_lubuntu](https://user-images.githubusercontent.com/13695767/39777698-c0ef8b0c-52f3-11e8-951f-b555a579c2a2.png)
