### ISSUE TITLE
TessBaseAPISetPageSegMode

### ISSUE THREAD

**Issue by tothpaul** [r1me/TTesseractOCR4#7]
under Tokyo 10.2.2 (Windows 8, french), the VCL Image demo returns "giﬁ'gégzgéégzizﬁséZi,." for eng-text.png until I comment out the line Tesseract.PageSegMode := TessPageSegMode(cbPageSegMode.ItemIndex);

the multi-page image returns nothing with the PageSegMode, and approximative text without it

![tesseract](https://user-images.githubusercontent.com/2483814/40909887-045979aa-67eb-11e8-9838-d4ac5a2f9591.png)

the console mode application works well for both images.

**Comment by r1me** [comment]
You are having similar issues as with #9. You are most likely using wrong data files. Please download data files from [https://github.com/tesseract-ocr/tessdata/](https://github.com/tesseract-ocr/tessdata/) as stated in the instructions. I'll be willing to assist if that's not the case.
